### ISSUE TITLE
Serialization and De-serialization of enum

### ISSUE THREAD

**Issue by vayalaivadivel** [consultingwerk/ListsAndEnumSamples#1]
Hi All, 
   Any one can share complete example of Serialization and De-serialization of enum from/to JSON

**Comment by mikefechner** [comment]
Have you had a look at the slide deck linked from the default.md document? Page 74 defines customer with an Enum Property Terms. Pg. 75 shows how to serialized Customer with the Enum property. Pg 78 is the deserialization. 

There are also samples in this repo.

**Comment by vayalaivadivel** [comment]
Thanks for your quick reply. I will check and let you know,

Thanks,
Vadivel PM
